"""Added a score aggregation column to question model to specify how it should be totaled

Revision ID: 11dde2b7f832
Revises: 440606a72202
Create Date: 2026-02-26 08:59:02.797360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11dde2b7f832'
down_revision = '440606a72202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_aggregation', sa.String(length=64), server_default='ranked', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('score_aggregation')

    # ### end Alembic commands ###
