"""empty message

Revision ID: 440606a72202
Revises: 8060ec38fbc6
Create Date: 2026-02-20 19:55:14.693447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440606a72202'
down_revision = '8060ec38fbc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.alter_column('report_month',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.alter_column('report_month',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
