"""empty message

Revision ID: 8060ec38fbc6
Revises: ca1a3b45cc92
Create Date: 2026-02-20 19:52:20.066187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8060ec38fbc6'
down_revision = 'ca1a3b45cc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.alter_column('report_month',
               existing_type=sa.INTEGER(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.alter_column('report_month',
               existing_type=sa.Date(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
