"""fresh schema with cascaded

Revision ID: a714e9a53925
Revises: 
Create Date: 2026-02-13 18:36:55.282680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a714e9a53925'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_name'), ['name'], unique=True)

    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_location'), ['location'], unique=True)

    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=64), nullable=False),
    sa.Column('question', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_question'), ['question'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_question_type'), ['question_type'], unique=False)

    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_timestamp'), ['timestamp'], unique=False)

    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_response_id'), ['response_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_response_id'))
        batch_op.drop_index(batch_op.f('ix_answer_question_id'))

    op.drop_table('answer')
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_timestamp'))
        batch_op.drop_index(batch_op.f('ix_response_store_id'))
        batch_op.drop_index(batch_op.f('ix_response_assessment_id'))

    op.drop_table('response')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_question_type'))
        batch_op.drop_index(batch_op.f('ix_question_question'))
        batch_op.drop_index(batch_op.f('ix_question_assessment_id'))

    op.drop_table('question')
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_location'))

    op.drop_table('store')
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_name'))

    op.drop_table('assessment')
    # ### end Alembic commands ###
