"""adjuted table args for response and made response report month manually entered

Revision ID: ca1a3b45cc92
Revises: fb7bb2d80101
Create Date: 2026-02-20 19:46:24.979644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1a3b45cc92'
down_revision = 'fb7bb2d80101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.alter_column('report_month',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_response_store_form_month'), type_='unique')
        batch_op.create_unique_constraint('uq_response_store_form_month', ['store_id', 'assessment_id', 'form_type', 'report_month'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_constraint('uq_response_store_form_month', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_response_store_form_month'), ['store_id', 'form_type', 'report_month'])
        batch_op.alter_column('report_month',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
