"""initial schema

Revision ID: fb7bb2d80101
Revises: 
Create Date: 2026-02-20 11:15:26.432473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7bb2d80101'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_name'), ['name'], unique=True)

    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_location'), ['location'], unique=True)

    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=64), nullable=False),
    sa.Column('question', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_question'), ['question'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_question_type'), ['question_type'], unique=False)

    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('report_month', sa.Date(), nullable=False),
    sa.Column('yes_count', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('percent_score', sa.Float(), nullable=False),
    sa.Column('form_type', sa.String(length=16), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'form_type', 'report_month', name='uq_response_store_form_month')
    )
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_form_type'), ['form_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_report_month'), ['report_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_timestamp'), ['timestamp'], unique=False)

    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_response_id'), ['response_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_response_id'))
        batch_op.drop_index(batch_op.f('ix_answer_question_id'))

    op.drop_table('answer')
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_timestamp'))
        batch_op.drop_index(batch_op.f('ix_response_store_id'))
        batch_op.drop_index(batch_op.f('ix_response_report_month'))
        batch_op.drop_index(batch_op.f('ix_response_form_type'))
        batch_op.drop_index(batch_op.f('ix_response_assessment_id'))

    op.drop_table('response')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_question_type'))
        batch_op.drop_index(batch_op.f('ix_question_question'))
        batch_op.drop_index(batch_op.f('ix_question_is_active'))
        batch_op.drop_index(batch_op.f('ix_question_assessment_id'))

    op.drop_table('question')
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_location'))
        batch_op.drop_index(batch_op.f('ix_store_is_active'))

    op.drop_table('store')
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_name'))

    op.drop_table('assessment')
    # ### end Alembic commands ###
