"""Added category to question table

Revision ID: fee66439fd69
Revises: 11dde2b7f832
Create Date: 2026-03-26 16:21:14.625260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee66439fd69'
down_revision = '11dde2b7f832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        # SQLite cannot add a NOT NULL column without a DEFAULT for existing rows.
        batch_op.add_column(
            sa.Column(
                'category',
                sa.String(length=64),
                nullable=False,
                server_default='Misc',
            )
        )
        batch_op.create_index(batch_op.f('ix_question_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_category'))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
